#!/usr/bin/env bash
# transfer file to client
if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
p_file="$1"
IP="$2"
USERNAME="$3"
P_ssh_key="$4"

scp -i "$P_ssh_key" -o StrictHostKeyChecking=no "$p_file" "$USERNAME@$IP:~/"

if [ $? -eq 0 ]; then
	echo "File transferred successfully."
else
	echo "File transfer failed."
	exit 1
fi
