#!/usr/bin/env bash
# this installs and configues nginxs on a fresh ubuntu
apt update -y
apt install nginx -y
echo "Hello World!" > /var/www/html/index.html

sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

nginx -t && nginx -s reload
