#!/usr/bin/env bash
# this installs and configues nginxs on a fresh ubuntu
sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i 's|root /var/www/html;|root /var/www/html;|' /etc/nginx/sites-available/default

sudo nginx -t && sudo nginx -s reload
curl localhost
