#!/usr/bin/env bash
# this installs and configues nginxs on a fresh ubuntu
sudo apt update -y
sudo apt install mginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo sed -i 's/# server_name _;server_name _;/' /etc/nginx/sites-available/default
sudo nginx -t
sudo nginx
curl localhost
