#!/usr/bin/env bash
#redirects to another page
sudo apt update -y
sudo apt install -y nginx

cat << EOF | sudo tee /etc/nginx/sites-available/default
server {
	listen 80;
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;
	}

	location /var/www/html;
	index index.html;
}
EOF
sudo systemctl restart nginx
