#!/usr/bin/env bash
#redirects to another page
sudo apt update -y
sudo apt install -y nginx

sudo systemctl enable nginx

sudo sed -i '/server_name_;/a \
	location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n }'
sudo nginx -t && sudo systemctl restart nginx
