#!/usr/bin/env bash
#not found

sudo apt update -y
sudo apt install -y nginx

sudo systemctl enable nginx
sudo systemctl start nginx

CONFIG_FILE=/etc/nginx/sites-available/default

sudo sed -i '/location \/redirect_me {/,/}/d' $CONFIG_FILE
sudo sed -i '/error_page 404/d' $CONFIG_FILE
sudo sed -i '/location = \/custom_404.html {/,/}/d' $CONFIG_FILE

sudo sed -i '/server_name _;/a \
    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n\n    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        root /var/www/html;\n        internal;\n    }' $CONFIG_FILE

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo chmod 644 /var/www/html/custom_404.html

sudo nginx -t && sudo systemctl restart nginx
