#!/usr/bin/env bash
#configure web-02
sudo apt update
sudo apt install -y nginx

HOSTNAME=$(hostname)

CONFIG_FILE="/etc/nginx/sites-available/default"
sudo sed -i '/server_name _;/a \tadd_header X-Served-By "$HOSTNAME";' $CONFIG_FILE

sudo nginx -t && sudo systemctl restart nginx
