#!/usr/bin/env bash
#Update package lists, ensure port 80 is the default

apt-get update -y

dpkg -l | grep -qw nginx || apt-get install -y nginx

systemctl enable nginx
systemctl start nginx

if ! ss -tlnp | grep -q ':80 ';
then

    sed -i 's/^\s*listen \[::\]:80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
    sed -i 's/^\s*listen \[::\]:80;/listen 80;/' /etc/nginx/sites-available/default
    
    systemctl restart nginx
fi
