#!/usr/bin/env bash
#Update package lists, ensure port 80 is the default

if ! command -v nginx &> /dev/null; then
    apt update && apt install -y nginx
fi

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default

systemctl restart nginx

systemctl enable nginx
