#!/usr/bin/env bash
# listening on port 98
PORT=98
if ! command -v nc &> /dev/null; then
	echo "netcat (nc) is required but not installed. Install it with 'sudo apt install netcat'."
	exit 1
fi
echo "listening on port $PORT..."
nc -lk 127.0.0.1 $PORT
