#!/usr/bin/env bash
# run nginx as nginx
dpkg -l | grep -qw nginx || apt-get update && apt-get install -y nginx

id -u nginx &>/dev/null || useradd -r -d /var/www -s /sbin/nologin nginx

sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default

sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf

chown -R nginx:nginx /var/www/html
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx

service nginx restart
